name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #-
      #  name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      - 
        name: Check Out Repo 
        uses: actions/checkout@v4
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push mainline/alpine
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: mainline-alpine.Dockerfile
          push: true
          tags: docker.io/denji/nginx-libressl:mainline-alpine
          cache-from: type=registry,ref=docker.io/denji/nginx-libressl:mainline-alpine
          cache-to: type=inline
      - 
        name: Build and push stable/alpine
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: stable-alpine.Dockerfile
          push: true
          tags: docker.io/denji/nginx-libressl:stable-alpine
          cache-from: type=registry,ref=docker.io/denji/nginx-libressl:stable-alpine
          cache-to: type=inline